# Generated by Django 6.0.5 on 2026-07-12 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_isbn10'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='gutenberg_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
