# Generated by Django 6.0.5 on 2026-08-07 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_readinglist'),
    ]

    operations = [
        migrations.AddField(
            model_name='readinglist',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
