# Generated by Django 6.0.5 on 2026-08-10 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_readinglist_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='readinglist',
            name='review_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='readinglist',
            name='sentiment',
            field=models.CharField(blank=True, choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], max_length=10, null=True),
        ),
    ]
